Resultaten wegschrijven in genormaliseerd datamodel. Voorlopig gesimuleerd als sqlite. Connectie met LSVI databank of andere masterdata nog uit te klaren?

In [88]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [89]:
import sqlite3
from datetime import datetime
import pandas as pd

from arcgis.gis import GIS

In [90]:
import os
import sys

# Get the absolute path of the folder above the notebook
parent_dir = os.path.abspath(os.path.join(os.getcwd(), ".."))

if parent_dir not in sys.path:
    sys.path.insert(0, parent_dir)

from src import utils

### Connectie naar databank

In [91]:
# Aanmaken 
def init_database(db_path="lsvi_resultaten_slank.sqlite"):
    conn = sqlite3.connect(db_path)
    cursor = conn.cursor()
    cursor.execute("PRAGMA foreign_keys = ON;")
    
    # Tabel 1: WaarnemingEvent
    cursor.execute("""
    CREATE TABLE IF NOT EXISTS waarneming_event (
        collectie_id TEXT PRIMARY KEY,
        global_id TEXT,
        user_name TEXT,
        bwk_plot_id TEXT,
        bwk_globalid TEXT,
        bwk_centroid_x REAL,
        bwk_centroid_y REAL,
        locatie_x REAL,
        locatie_y REAL,
        EPSG INTEGER,
        doel_habitattype TEXT,
        created_date DATETIME,
        last_edited_date DATETIME,
        timestamp_measurement DATETIME
    );
    """)
    
    # Tabel 2: Resultaat (Nu ook voor de losse soorten!)
    cursor.execute("""
    CREATE TABLE IF NOT EXISTS resultaat (
        resultaat_id INTEGER PRIMARY KEY AUTOINCREMENT,
        collectie_id TEXT,
        voorwaarde_id INTEGER,
        vraag_id TEXT,
        subvraag TEXT,
        waarde_tekst TEXT,
        waarde_numeriek REAL,
        FOREIGN KEY (collectie_id) REFERENCES waarneming_event(collectie_id) ON DELETE CASCADE
    );
    """)
    conn.commit()
    return conn

# Helperfunctie om ArcGIS Epoch Milliseconds om te zetten naar een ISO string
def format_agol_date(epoch_ms):
    if epoch_ms is None:
        return None
    # AGOL timestamps zijn in milliseconden, Python verwacht seconden
    return datetime.fromtimestamp(epoch_ms / 1000.0).strftime('%Y-%m-%d %H:%M:%S')

### Run ETL

In [93]:
# Uitvoering
# Joost to do: credentials uit key vault of environment
# Load secrets into environment
LOCAL_DB = "G:\\Mijn Drive\\keepass_db.kdbx"
ENTRY_TITLE = "AGOL"
AGOL_URL = "https://gisservices.inbo.be/portal"

AGOL_USER, AGOL_PASS = utils.load_keepass_credentials(
        db_path=LOCAL_DB, entry_name=ENTRY_TITLE
    )

feature_layer_item_id = "f8866108438b44cf89e9c0c31cc18c1c"
today = datetime.now().strftime("%Y%m%d")
db_path = f"../output/lsvi_resultaten_{today}.sqlite"

FEATURE_LAYER_NAME = "xlsform_hab1-4"

# Verbinden met AGOL
print(f"Verbinden met {AGOL_URL}...")
gis = GIS(AGOL_URL, AGOL_USER, AGOL_PASS)
# Get feature layer id from name
layer_items = gis.content.search(FEATURE_LAYER_NAME, item_type='Feature Layer', max_items=10)
# Exclude item in list if ends with _form
layer_items = [item for item in layer_items if not item.title.endswith('_form')]
feature_layer_item_id = layer_items[0].id if layer_items else None

print(f"Feature layer {feature_layer_item_id} downloaden...")
feature_layer = layer_items[0].layers[0]

# Vraag alle records op (1=1) inclusief WGS84 geometrie (out_sr=4326)
features_result = feature_layer.query(where="1=1", out_sr=4326)
print(f"Succesvol {len(features_result.features)} features gedownload. Start verwerking...")

field_aliases = {
    f.name: f.alias for f in feature_layer.properties.fields
} if hasattr(feature_layer, 'properties') else {}

ℹ️ Inloggegevens voor 'AGOL' zijn al actief in deze sessie. Prompt overgeslagen.
Verbinden met https://gisservices.inbo.be/portal...
Feature layer 55a62509e1c749118a9217622dd5fed4 downloaden...
Connection to 172.31.1.204:9876 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
(Error Code: 500)

TypeError: 'NoneType' object is not subscriptable

In [96]:
layer_items[0].layers

Connection to 172.31.1.204:9876 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
(Error Code: 500)

In [ ]:
# def run_etl(agol_url, username, password, feature_layer_item_id, db_path="lsvi_resultaten_slank.sqlite"):

conn = init_database(db_path)
cursor = conn.cursor()

# 4. Loop door ELKE feature uit de layer
for feature in features_result.features:
    geom = feature.geometry if feature.geometry else {}
    attrs = feature.attributes if feature.attributes else {}
    
    # Controleer of de cruciale collectie_id aanwezig is
    collectie_id = attrs.get('collectie_id')
    if not collectie_id:
        collectie_id = attrs.get('globalid')
        
    # Metadata extraheren en parsen
    global_id = attrs.get('globalid')
    user_name = attrs.get('username')
    habitat_keuze = attrs.get('habitat_keuze')
    bwk_plot_id = attrs.get('bwk_plot_id')
    bwk_globalid = attrs.get('bwk_globalid')
    bwk_centroid_x = attrs.get('bwk_centroid_x')
    bwk_centroid_y = attrs.get('bwk_centroid_y')
    
    created_date_txt = format_agol_date(attrs.get('datum'))
    last_edited_date_txt = format_agol_date(attrs.get('last_edited_date'))
    
    # Tijdstip van het bezoek bepalen (Datum-veld + Uur-veld combineren)
    datum_txt = format_agol_date(attrs.get('datum'))
    uur_txt = attrs.get('uur')  # string zoals "14:59"
    tijdstip_waarneming = f"{datum_txt.split(' ')[0]} {uur_txt}" if datum_txt and uur_txt else datum_txt

    # Geometrie
    x = geom.get('x')
    y = geom.get('y')
    epsg = geom.get('spatialReference', {}).get('wkid')

    # WaarnemingEvent wegschrijven
    cursor.execute("""
        INSERT INTO waarneming_event (
            collectie_id, 
            global_id, 
            user_name, 
            bwk_plot_id,
            bwk_globalid,
            bwk_centroid_x,
            bwk_centroid_y,
            locatie_x, 
            locatie_y, 
            epsg, 
            doel_habitattype,  
            created_date, 
            last_edited_date,
            timestamp_measurement
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        ON CONFLICT(collectie_id) DO UPDATE SET
            global_id=excluded.global_id,
            user_name=excluded.user_name,
            bwk_plot_id=excluded.bwk_plot_id,
            bwk_globalid=excluded.bwk_globalid,
            bwk_centroid_x=excluded.bwk_centroid_x,
            bwk_centroid_y=excluded.bwk_centroid_y,
            locatie_x=excluded.locatie_x,
            locatie_y=excluded.locatie_y,
            epsg=excluded.epsg,
            doel_habitattype=excluded.doel_habitattype,
            created_date=excluded.created_date,
            last_edited_date=excluded.last_edited_date,
            timestamp_measurement=excluded.timestamp_measurement;
        """, (collectie_id, global_id, user_name, bwk_plot_id, bwk_globalid, bwk_centroid_x, bwk_centroid_y, x, y, epsg, habitat_keuze, created_date_txt, last_edited_date_txt, tijdstip_waarneming))
    
    # Resultaten wegschrijven
    # Eerst collectieID wissen voor overschrijven
    cursor.execute("DELETE FROM resultaat WHERE collectie_id = ?", (collectie_id,))
conn.commit()
conn.close()

In [65]:
sqlite_path = "../output/lsvi_resultaten_20260727.sqlite"

conn = sqlite3.connect(sqlite_path)
results = pd.read_sql_query("SELECT * FROM waarneming_event LIMIT 10;", conn)
display(results)
conn.close()

,collectie_id,global_id,user_name,bwk_plot_id,bwk_globalid,bwk_centroid_x,bwk_centroid_y,locatie_x,locatie_y,EPSG,doel_habitattype,created_date,last_edited_date,timestamp_measurement
0,{6E9EE85B-D1F2-42BE-8B2B-09172A0F685B},{6E9EE85B-D1F2-42BE-8B2B-09172A0F685B},None,NaN,NaN,NaN,NaN,0.000000,0.000000,4326,1310_pol,2026-07-22 12:00:00,2026-07-22 10:11:02,2026-07-22 10:08
1,{94B23600-A89A-47BE-9A82-4FE9637BC3C3},{94B23600-A89A-47BE-9A82-4FE9637BC3C3},None,NaN,{42CD62CB-10B2-48B7-A8BB-0A2B5EE58859},5.518337e+12,6.627371e+14,0.000000,0.000000,4326,3130_aom,2026-07-22 12:00:00,2026-07-22 10:18:24,2026-07-22 10:15
2,{957EF476-BE5F-42E5-A505-49416CC55429},{957EF476-BE5F-42E5-A505-49416CC55429},None,,{8706A9FF-4A60-497E-87F5-EF853B21B8BC},4.340605e+13,6.651825e+14,3.898538,51.171811,4326,2330_dw,2026-07-24 12:00:00,2026-07-24 15:30:42,2026-07-24 15:06
3,{9D6829F0-B79C-4209-A428-65B93E547F6D},{9D6829F0-B79C-4209-A428-65B93E547F6D},None,NaN,NaN,NaN,NaN,0.000000,0.000000,4326,1310_pol,2026-07-22 12:00:00,2026-07-22 10:09:13,2026-07-22 10:08

In [81]:
for feature in features_result.features:
    print(feature.attributes.get('globalid'))

{6E9EE85B-D1F2-42BE-8B2B-09172A0F685B}
{94B23600-A89A-47BE-9A82-4FE9637BC3C3}
{957EF476-BE5F-42E5-A505-49416CC55429}
{9D6829F0-B79C-4209-A428-65B93E547F6D}

In [ ]:
# def run_etl(agol_url, username, password, feature_layer_item_id, db_path="lsvi_resultaten_slank.sqlite"):

sqlite_path = "../output/lsvi_resultaten_20260727.sqlite"

conn = sqlite3.connect(sqlite_path)
cursor = conn.cursor()

for feature in features_result.features:
    geom = feature.geometry if feature.geometry else {}
    attrs = feature.attributes if feature.attributes else {}
    # Loop dynamisch door alle kolommen van de feature
    for key, value in attrs.items():
        # Sla lege cellen, systeemenmerken en layout-hulpmiddelen over
        if value is None:
            continue

        # Extraheer het getal (VoorwaardeID) als de kolom begint met 'vrg_'
        voorwaarde_id = None
        habitattype = None
        subvraag = None

        if key.startswith("vrg_"):
            clean_key = key[4:]

            # Controleer of het een matrixvraag betreft
            if "_matrix_" in clean_key:
                # Bv. '736_1310_zv_matrix_0' -> base_part = '736_1310_zv'
                base_part = clean_key.split("_matrix_")[0]
                # Ophalen van de weergavenaam (subvraag) uit onze lookup dict
                subvraag = field_aliases.get(key)
            else:
                base_part = clean_key
                subvraag = None  # Geen matrix, dus geen subvraag

            # Ontleed voorwaarde_id en habitattype uit base_part (bv. '712_1310_zk')
            parts = base_part.split("_", 1)
            if parts[0].isdigit():
                voorwaarde_id = int(parts[0])
                if len(parts) > 1:
                    habitattype = parts[1]  # Bv. '1310_zk' of '1310_zv'
        
            # Gegevenstype bepalen voor waarde_numeriek
            waarde_numeriek = None
            if isinstance(value, (int, float)):
                waarde_numeriek = float(value)
            elif isinstance(value, str):
                try:
                    waarde_numeriek = float(value)
                except ValueError:
                    pass

            # Afhandeling van select_multiple (komma-gescheiden waarden)
            if isinstance(value, str) and "," in value:
                soorten = [s.strip() for s in value.split(",")]
                for soort in soorten:
                    if soort:
                        cursor.execute("""
                            INSERT INTO resultaat (
                                collectie_id, voorwaarde_id, vraag_id, subvraag, waarde_tekst, waarde_numeriek
                            )
                            VALUES (?, ?, ?, ?, ?, ?);
                        """, (collectie_id, voorwaarde_id, key, subvraag,  soort, waarde_numeriek))
            else:
                # Normale vraag / enkele waarde
                cursor.execute("""
                    INSERT INTO resultaat (
                        collectie_id, voorwaarde_id, vraag_id, subvraag, waarde_tekst, waarde_numeriek
                    )
                    VALUES (?, ?, ?, ?, ?, ?);
                """, (collectie_id, voorwaarde_id, key, subvraag, str(value), waarde_numeriek))

# Sluit alles netjes af
conn.commit()
conn.close()
print("ETL afgerond. De SQLite database is volledig up-to-date.")

ETL afgerond. De SQLite database is volledig up-to-date.

In [ ]:
sqlite_path = "../output/lsvi_resultaten_20260727.sqlite"
collectie_id = "{957EF476-BE5F-42E5-A505-49416CC55429}"

conn = sqlite3.connect(sqlite_path)
results = pd.read_sql_query(f"SELECT * FROM resultaat WHERE collectie_id = '{collectie_id}'", conn)
results.head(30)
conn.close()

In [87]:
results.head(30)

,resultaat_id,collectie_id,voorwaarde_id,vraag_id,subvraag,waarde_tekst,waarde_numeriek
0,89,{957EF476-BE5F-42E5-A505-49416CC55429},NaN,habitat_keuze,NaN,1310_pol,NaN
1,90,{957EF476-BE5F-42E5-A505-49416CC55429},NaN,globalid,NaN,{6E9EE85B-D1F2-42BE-8B2B-09172A0F685B},NaN
2,91,{957EF476-BE5F-42E5-A505-49416CC55429},93.0,vrg_93_1310_pol,NaN,s,NaN
3,92,{957EF476-BE5F-42E5-A505-49416CC55429},NaN,created_user,NaN,joost.neujens@inbo.be,NaN
4,93,{957EF476-BE5F-42E5-A505-49416CC55429},NaN,datum,NaN,1784714400000,1.784714e+12
5,94,{957EF476-BE5F-42E5-A505-49416CC55429},NaN,uur,NaN,10:08,NaN
6,95,{957EF476-BE5F-42E5-A505-49416CC55429},NaN,created_date,NaN,1784707862623,1.784708e+12
7,96,{957EF476-BE5F-42E5-A505-49416CC55429},NaN,objectid,NaN,2,2.000000e+00
8,97,{957EF476-BE5F-42E5-A505-49416CC55429},1337.0,vrg_1337_1310_pol,NaN,90_95perc,NaN
9,98,{957EF476-BE5F-42E5-A505-49416CC55429},NaN,hab1,NaN,1310_pol,NaN
10,99,{957EF476-BE5F-42E5-A505-49416CC55429},NaN,last_edited_date,NaN,1784707862623,1.784708e+12
11,100,{957EF476-BE5F-42E5-A505-49416CC55429},NaN,lsvi_opstellen,NaN,ja,NaN
12,101,{957EF476-BE5F-42E5-A505-49416CC55429},NaN,last_edited_user,NaN,joost.neujens@inbo.be,NaN
13,102,{957EF476-BE5F-42E5-A505-49416CC55429},NaN,habitat_keuze,NaN,3130_aom,NaN
14,103,{957EF476-BE5F-42E5-A505-49416CC55429},NaN,globalid,NaN,{94B23600-A89A-47BE-9A82-4FE9637BC3C3},NaN
15,104,{957EF476-BE5F-42E5-A505-49416CC55429},2040.0,vrg_2040_3130_aom,NaN,30_40perc,NaN
16,105,{957EF476-BE5F-42E5-A505-49416CC55429},805.0,vrg_805_3130_aom,NaN,20_30perc,NaN
17,106,{957EF476-BE5F-42E5-A505-49416CC55429},903.0,vrg_903_3130_aom,NaN,10_20perc,NaN
18,107,{957EF476-BE5F-42E5-A505-49416CC55429},NaN,created_user,NaN,joost.neujens@inbo.be,NaN
19,108,{957EF476-BE5F-42E5-A505-49416CC55429},2321.0,vrg_2321_3130_aom,NaN,66,6.600000e+01
20,109,{957EF476-BE5F-42E5-A505-49416CC55429},NaN,datum,NaN,1784714400000,1.784714e+12
21,110,{957EF476-BE5F-42E5-A505-49416CC55429},NaN,uur,NaN,10:15,NaN
22,111,{957EF476-BE5F-42E5-A505-49416CC55429},NaN,created_date,NaN,1784708304948,1.784708e+12
23,112,{957EF476-BE5F-42E5-A505-49416CC55429},NaN,objectid,NaN,3,3.000000e+00
24,113,{957EF476-BE5F-42E5-A505-49416CC55429},464.0,vrg_464_3130_aom_matrix_2,Oeverkruid,f,NaN
25,114,{957EF476-BE5F-42E5-A505-49416CC55429},464.0,vrg_464_3130_aom_matrix_0,Witte waterranonkel,o,NaN
26,115,{957EF476-BE5F-42E5-A505-49416CC55429},464.0,vrg_464_3130_aom_matrix_9,Moerassmele,80_90perc,NaN
27,116,{957EF476-BE5F-42E5-A505-49416CC55429},464.0,vrg_464_3130_aom_matrix_5,Moerasweegbree,60_70perc,NaN
28,117,{957EF476-BE5F-42E5-A505-49416CC55429},NaN,hab1,NaN,3130_aom,NaN
29,118,{957EF476-BE5F-42E5-A505-49416CC55429},1041.0,vrg_1041_3130_aom,NaN,s,NaN

### Load data export

In [ ]:
sqlite_path = "../output/lsvi_resultaten.sqlite"
conn = sqlite3.connect(sqlite_path)

tables = pd.read_sql_query(
    "SELECT name FROM sqlite_master WHERE type='table' ORDER BY name;",
    conn
)
print("Tables in database:")
display(tables)

print("\nWaarnemingEvent sample:")
display(pd.read_sql_query("SELECT * FROM waarneming_event LIMIT 20;", conn))

print("\nResultaat sample:")
results = pd.read_sql_query("SELECT * FROM resultaat WHERE collectie_id = '2e5acf0e-cef5-4d29-ad06-96900a597a7b';", conn)
display(results)

conn.close()